name: Docker Image CI

on:
  push:
    branches: [ '**' ]
    tags: ['*']
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - {tag: "", dockerfile: "./Dockerfile.default", platforms: "linux/amd64,linux/arm64", build_args: "" }
          - {
              tag: "openblas", 
              dockerfile: "./Dockerfile.default", 
              platforms: "linux/amd64,linux/arm64", 
              build_args: "EXTRA_DEPS=\"libopenblas-dev\" CMAKE_ARGS=\"-DGGML_OPENBLAS=On\""
            }
          - {tag: "-cuda11", dockerfile: "./Dockerfile.cuda11", platforms: "linux/amd64", build_args: "" }
          - {tag: "-cuda12", dockerfile: "./Dockerfile.cuda12", platforms: "linux/amd64", build_args: "" }

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm68/v8

    - name: Login to GH ContainerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ravenscroftj
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push incremental
      uses: docker/build-push-action@v4.1.1
      if: (!startsWith(github.ref, 'refs/tags/'))
      with:
        file: ${{matrix.config.dockerfile}}
        push: true
        tags: ghcr.io/ravenscroftj/turbopilot:nightly${{matrix.config.tag}}-${{ github.sha }}
        context: ${{github.workspace}}
        platforms: ${{matrix.config.platforms}}
        build-args: ${{matrix.config.build_args}}


    - name: Build and push release (Main Latest Build)
      uses: docker/build-push-action@v4
      if: startsWith(github.ref, 'refs/tags/') && matrix.config.tag == ''
      with:
        file: ${{matrix.config.dockerfile}}
        push: true
        tags: ghcr.io/ravenscroftj/turbopilot:${{ github.ref_name }}, ghcr.io/ravenscroftj/turbopilot:latest
        context: ${{github.workspace}}
        platforms: ${{matrix.config.platforms}} 
        build-args: ${{matrix.config.build_args}}


    - name: Build and push release (Accelerated Builds)
      uses: docker/build-push-action@v4
      if: startsWith(github.ref, 'refs/tags/') && matrix.config.tag != ''
      with:
        file: ${{matrix.config.dockerfile}}
        push: true
        tags: ghcr.io/ravenscroftj/turbopilot:${{ github.ref_name }}${{matrix.config.tag}}
        context: ${{github.workspace}}
        platforms: ${{matrix.config.platforms}}
        build-args: ${{matrix.config.build_args}}
